Initial version
peiffer-innovations/json_dynamic_widget_plugin_js pull request #1
Opened 2023-07-05 13:12 UTC by crisperit

2023-07-05 22:11 UTC, jpeiffer requested changes

2023-07-05 22:11 UTC, jpeiffer commented on lib/src/components/functions/js/service/js_service.dart
> +  static JsService Get() {
I'd prefer this to be `static JsService get instance` as that's a more common pattern than having a function named `Get`.

2023-07-05 22:11 UTC, jpeiffer commented on lib/src/components/functions/js/js.dart
> +        throw Exception('Error evaluating JS: $e');
It's not really clear why this is better than just letting the original exception be thrown.

It's good practice if you catch an exception to log it out via a `Logger`.

2023-07-06 12:03 UTC, crisperit commented on lib/src/components/functions/js/js.dart
> +        throw Exception('Error evaluating JS: $e');
I want to only wrap the error to provide more context to it

I think that core should have some general mechanism to handle Future's and Exceptions 

For example in such the exception case someone might want to show some error dialog rather than never be informed about that Exception

2023-07-13 00:20 UTC, merged